#v1
# services:
#   online_menu_web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: tajievolimjon/online_menu_web_api
#     container_name: online_menu_web
#     environment:
#       - DJANGO_SETTINGS_MODULE=server.settings.production
#       - DB_NAME=onlinemenudb
#       - DB_USER=postgres
#       - DB_PASSWORD=online_menu2024
#       - DB_HOST=online_menu_db
#       - DB_PORT=5432
#     ports:
#       - "8000:8000"
#     depends_on:
#       - online_menu_db
      # networks:
      #   - menu-dev

#   online_menu_db:
#     image: postgres:13
#     container_name: online_menu_db
#     ports:
#       - "5400:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: online_menu2024
#       POSTGRES_DB: onlinemenudb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
      # networks:
      #   - menu-dev

# networks:
#   menu-dev:

# volumes:
#   postgres_data:
 
#docker compose exec online_menu_web python manage.py migrate

#*******************************************************************************

# #v2
# services:
#   armut_api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: tajievolimjon/armut_api
#     container_name: armut_api
#     environment:
#       - DJANGO_SETTINGS_MODULE=server.settings.production
#       - DB_NAME=armutmenudb
#       - DB_USER=postgres
#       - DB_PASSWORD=armutmenu2024
#       - DB_HOST=armut_api_db
#       - DB_PORT=5432
#     ports:
#       - "8006:8080"
#     depends_on:
#       - armut_api_db
#     networks:
#       - armut-dev

#   armut_api_db:
#     image: postgres:13
#     container_name: armut_api_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: armutmenu2024
#       POSTGRES_DB: armutmenudb
#     ports:
#       - "5436:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - armut-dev


# networks:
#   armut-dev:

# volumes:
#   postgres_data:

# #docker compose exec armut_api python manage.py migrate

#*******************************************************************************

#v3
services:
  merve_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tajievolimjon/merve_api
    container_name: merve_api
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings.production
      - DB_NAME=mervemenudb
      - DB_USER=postgres
      - DB_PASSWORD=mervemenu2024
      - DB_HOST=merve_api_db
      - DB_PORT=5432
    ports:
      - "8006:8080"
    depends_on:
      - merve_api_db
    networks:
      - merve-dev

  merve_api_db:
    image: postgres:13
    container_name: merve_api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mervemenu2024
      POSTGRES_DB: mervemenudb
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - merve-dev


networks:
  merve-dev:

volumes:
  postgres_data:

#docker compose exec merve_api python manage.py migrate

